<a href="https://colab.research.google.com/github/practice-grounds-wpaarth24/Machine_Learning/blob/main/LR_Basic_Program_Idea.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
X = np.random.randint(2,100,50)
X

array([36, 32, 47, 57, 32, 95, 24, 71, 19, 82, 41, 53, 64, 34, 25, 43, 68,
        9, 80, 95, 54, 27, 93, 58, 94, 40, 26, 58, 68, 91, 53, 30, 33, 39,
       87, 37, 83, 20, 49,  8, 11, 91, 80, 17, 82, 35, 11, 28, 57, 41])

In [ ]:
Y = X+5
Y

array([ 41,  37,  52,  62,  37, 100,  29,  76,  24,  87,  46,  58,  69,
        39,  30,  48,  73,  14,  85, 100,  59,  32,  98,  63,  99,  45,
        31,  63,  73,  96,  58,  35,  38,  44,  92,  42,  88,  25,  54,
        13,  16,  96,  85,  22,  87,  40,  16,  33,  62,  46])

In [ ]:
import plotly.express as px
px.scatter(x=X,y=Y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train.reshape(-1, 1),Y_train)

LinearRegression()

In [ ]:
predictions = model.predict(X_test.reshape(-1, 1))

In [ ]:
model.predict([[100]])

array([105.])